CREATE TABLE IF NOT EXISTS trucks (
    id CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    license_plate VARCHAR(20) NOT NULL,
    make_model VARCHAR(120) NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX trucks_license_plate_unique ON trucks (license_plate);

