name: Deploy to Beget

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment script on Beget
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USER }}
          key: ${{ secrets.BEGET_SSH_KEY }}
          port: ${{ secrets.BEGET_PORT || '22' }}
          script: bash ~/bitrix.vsepeski.ru/deploy.sh

